name: Example 3 - Manual Invocation With Parameters
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      name:
        description: 'The name to say hello to'
        required: false
        default: 'Manual Workflow'

jobs:
  echo-hello:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Run script
        run: |
          bash hello.sh ${{ github.event.inputs.stage || 'Workflow' }}
