name: Example 5 - CDK With Environments
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.8.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.10

      - name: Install Poetry
        run: |
          pip install -U pip
          pip install wheel
          pip install poetry

      - name: Install dependencies
        run: |
          make example-5-install

      - name: Unit tests
        run: |
          make example-5-unit-tests
